// Mocks generated by Mockito 5.4.5 from annotations
// in mobile/test/feature/transaction/income_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile/apis/income/income_api.dart' as _i2;
import 'package:mobile/apis/income/models/income_model.dart' as _i4;
import 'package:mobile/apis/wallets/models/wallet_model.dart' as _i6;
import 'package:mobile/apis/wallets/wallet_api.dart' as _i5;
import 'package:mobile/features/transaction/service/cate_income_service.dart'
    as _i7;
import 'package:mobile/features/transaction/service/gemini_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IncomeServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncomeServices extends _i1.Mock implements _i2.IncomeServices {
  MockIncomeServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.IncomeModel>> listIncome() =>
      (super.noSuchMethod(
            Invocation.method(#listIncome, []),
            returnValue: _i3.Future<List<_i4.IncomeModel>>.value(
              <_i4.IncomeModel>[],
            ),
          )
          as _i3.Future<List<_i4.IncomeModel>>);

  @override
  _i3.Future<_i4.IncomeModel?> createIncome(_i4.IncomeModel? income) =>
      (super.noSuchMethod(
            Invocation.method(#createIncome, [income]),
            returnValue: _i3.Future<_i4.IncomeModel?>.value(),
          )
          as _i3.Future<_i4.IncomeModel?>);
}

/// A class which mocks [WalletServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletServices extends _i1.Mock implements _i5.WalletServices {
  MockWalletServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.WalletModel>> listWallet() =>
      (super.noSuchMethod(
            Invocation.method(#listWallet, []),
            returnValue: _i3.Future<List<_i6.WalletModel>>.value(
              <_i6.WalletModel>[],
            ),
          )
          as _i3.Future<List<_i6.WalletModel>>);

  @override
  _i3.Future<_i6.WalletModel?> createWallet(_i6.WalletModel? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#createWallet, [wallet]),
            returnValue: _i3.Future<_i6.WalletModel?>.value(),
          )
          as _i3.Future<_i6.WalletModel?>);
}

/// A class which mocks [CateIncomeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCateIncomeService extends _i1.Mock implements _i7.CateIncomeService {
  MockCateIncomeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i8.GeminiService {
  MockGeminiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> processText(String? ocrText, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#processText, [ocrText, type]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
