// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAd7nOmwG9Q3So1hcT6TbYscWAuJM4Skk',
    appId: '1:920894541622:web:91b1e4769e814a42f3ad97',
    messagingSenderId: '920894541622',
    projectId: 'tracking-expense-79899',
    authDomain: 'tracking-expense-79899.firebaseapp.com',
    storageBucket: 'tracking-expense-79899.firebasestorage.app',
    measurementId: 'G-SR1K82QKLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFTr6iXT0e6T_XylX-M16pK-t6sObefw',
    appId: '1:920894541622:android:5faf2fb5ebc9b159f3ad97',
    messagingSenderId: '920894541622',
    projectId: 'tracking-expense-79899',
    storageBucket: 'tracking-expense-79899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbdh9d5rW36cdz7_TLrFjkOTWbuoa5f2A',
    appId: '1:920894541622:ios:d82108a2ea2b0a45f3ad97',
    messagingSenderId: '920894541622',
    projectId: 'tracking-expense-79899',
    storageBucket: 'tracking-expense-79899.firebasestorage.app',
    iosBundleId: 'com.example.monitorTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbdh9d5rW36cdz7_TLrFjkOTWbuoa5f2A',
    appId: '1:920894541622:ios:d82108a2ea2b0a45f3ad97',
    messagingSenderId: '920894541622',
    projectId: 'tracking-expense-79899',
    storageBucket: 'tracking-expense-79899.firebasestorage.app',
    iosBundleId: 'com.example.monitorTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAd7nOmwG9Q3So1hcT6TbYscWAuJM4Skk',
    appId: '1:920894541622:web:8dbd4c9b8b7fcc93f3ad97',
    messagingSenderId: '920894541622',
    projectId: 'tracking-expense-79899',
    authDomain: 'tracking-expense-79899.firebaseapp.com',
    storageBucket: 'tracking-expense-79899.firebasestorage.app',
    measurementId: 'G-EVH2N4M8LF',
  );

}