name: Mobile CI

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main, develop ]

jobs:
    test:
      name: Test and analyze
      runs-on: ubuntu-22.04
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'gradle'
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.x'
            channel: 'stable'
            cache: true
  
        - name: Install dependencies
          run: flutter pub get
  
        - name: Verify formatting
          run: dart format --output=none --set-exit-if-changed .
  
        - name: Run tests
          run: flutter test --coverage
  
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
  
        - name: Notify Slack - Test
          run: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Build completed successfully!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
    
    build-android:
     name: Build Android App
     needs: test
     runs-on: ubuntu-22.04

     steps:
       - uses: actions/checkout@v4
 
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: 'gradle'
 
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.x'
           channel: 'stable'
           cache: true
 
       - name: Install dependencies
         run: flutter pub get
 
       - name: Build debug APK
         run: flutter build apk --debug
 
       - name: Upload debug APK
         uses: actions/upload-artifact@v4
         with:
           name: app-debug
           path: build/app/outputs/flutter-apk/app-debug.apk
 
       - name: Notify Slack - Build Completed
         run: |
           curl -X POST -H 'Content-type: application/json' --data '{"text":"Build completed successfully!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
